services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TrackBus
      MYSQL_USER: laxman
      MYSQL_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - tmsb-net
    restart: unless-stopped

  auth-server:
    build:
      context: ./backend
    container_name: auth-server
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_USER=laxman
      - DB_PASSWORD=root
      - DB_NAME=TrackBus
    depends_on:
      - mysql-db
    networks:
      - tmsb-net
    volumes:
      - "D:/Semester 6/Final Year Project Module/FYP Development/TrackMySchoolBus/backend:/app"

    restart: unless-stopped

  ws-server:
    build:
      context: ./WebSocketServer
    container_name: ws-server
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
    - SECRET_KEY=lsdlskdnldsknvlkn
    networks:
      - tmsb-net
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=u1WkiYMPRLaNwpvMb8Xx4A
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - tmsb-net
    restart: unless-stopped

volumes:
  mysql-data: {}
  kafka-data: {}

networks:
  tmsb-net:
